networks:
  docker:
    name: docker

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "{PROMETHEUS_PORT:-9090}:9090"
    networks:
      - docker
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.2.0-17567790421
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD={PASSWORD:-pass}
      - GF_SECURITY_ADMIN_USER={USER:-admin}
    ports:
      - "{GRAFANA_PORT:-3000}:3000"
    networks:
      - docker
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
